### ISSUE TITLE
Conjuntos Y Relaciones

### ISSUE THREAD

**Issue by Erick-3as** [SistemasTecTlaxiaco/mapa-mental-Erick-3as#2]
[CONJUNTOS Y RELACIONES-erick.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-Erick-3as/files/7274482/CONJUNTOS.Y.RELACIONES-erick.pdf)

**Comment by RicardoMtzSts** [comment]
Manejo conceptual y manejo del tema (notable);Relación entre conceptos incluidos en el mapa (excelente);Calidad de presentación (excelente);Jerarquía(excelente).
total: 19.4/20      calificación: 19.4% / 20%
Calificado por Ricardo Martínez Santos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
